"""empty message

Revision ID: 0f43856d2e87
Revises: 4a59b98d01c4
Create Date: 2023-06-13 21:07:36.411694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f43856d2e87'
down_revision = '4a59b98d01c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id_book', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id_author', sa.String(), nullable=False),
    sa.Column('id_genre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_author'], ['author.id'], ),
    sa.ForeignKeyConstraint(['id_genre'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('id_book'),
    sa.UniqueConstraint('id_book')
    )
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('book')
    # ### end Alembic commands ###
