"""empty message

Revision ID: 190b300a1c59
Revises: 758285038f47
Create Date: 2023-06-16 16:56:38.239206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '190b300a1c59'
down_revision = '758285038f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approve_admin', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('approved_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('return_admin', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('returned_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('admin_approve')
        batch_op.drop_column('return_date')
        batch_op.drop_column('approve_date')
        batch_op.drop_column('admin_return')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_return', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('approve_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('return_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('admin_approve', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('returned_date')
        batch_op.drop_column('return_admin')
        batch_op.drop_column('approved_date')
        batch_op.drop_column('approve_admin')

    # ### end Alembic commands ###
