"""empty message

Revision ID: 61b4039749ef
Revises: c05eafd0dc92
Create Date: 2023-06-15 09:00:41.962938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b4039749ef'
down_revision = 'c05eafd0dc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_author',
    sa.Column('book_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], name='book_author_author_id_fkey'),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='book_author_book_id_fkey'),
    sa.PrimaryKeyConstraint('book_id', 'author_id', name='book_author_pkey')
    )
    # ### end Alembic commands ###
