"""empty message

Revision ID: 758285038f47
Revises: 1be2a9889d34
Create Date: 2023-06-16 15:09:24.301710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758285038f47'
down_revision = '1be2a9889d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
