"""empty message

Revision ID: de6c6eaf84d8
Revises: 61b4039749ef
Create Date: 2023-06-16 10:53:08.569874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6c6eaf84d8'
down_revision = '61b4039749ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_approve', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('admin_return', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('requested_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('approve_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('return_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowed', schema=None) as batch_op:
        batch_op.drop_column('return_date')
        batch_op.drop_column('approve_date')
        batch_op.drop_column('requested_date')
        batch_op.drop_column('admin_return')
        batch_op.drop_column('admin_approve')

    # ### end Alembic commands ###
